In [9]:
import numpy as np

In [10]:
arr = [1, 2, 3, 4, 5]
print("일반 배열 슬라이싱(인덱싱)")
print(arr[1:3:])
print(arr[1:3])
print(arr[:])
arr2 = [[1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]]
print(arr2[0][1])
print(arr2[0])
print(arr2[0:3])
print(arr2[0:3][0:2])
print(arr2[1][1:3])

print("numpy 배열 슬라이싱")
arr3 = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])
print(arr3[1][2])
print(arr3[1, 2])
print(arr3[0:3])
print(arr3[0:3][0])
print(arr3[0:3, 0])
print(arr3[0:3:2, 0:2])
print(arr3[[0, 1, 2], 0:2])
print(arr3[[0, 1, 2], [0, 1, 2]])

일반 배열 슬라이싱(인덱싱)
[2, 3]
[2, 3]
[1, 2, 3, 4, 5]
2
[1, 2, 3, 4]
[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[[1, 2, 3, 4], [5, 6, 7, 8]]
[6, 7]
numpy 배열 슬라이싱
7
7
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]
[1 5 9]
[[ 1  2]
 [ 9 10]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
